# Generated by Django 5.1 on 2024-08-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
